"""Generate the store-only shell stylesheet without shrinking Spreadshop's rem units.
Run after changing style.css or brand.css. The site's rem is 10px; Spreadshop expects
16px. Convert only first-party shell rem lengths, leaving provider CSS untouched.
"""
from pathlib import Path
import re
ROOT = Path(__file__).resolve().parents[1]
def build():
    chunks = []
    for name in ('style.css', 'brand.css'):
        source = (ROOT / 'css' / name).read_text()
        source = re.sub(r'(-?\d*\.?\d+)rem\b', lambda m: f'{float(m[1]) * 10:g}px', source)
        chunks.append(f'/* Source: css/{name} */\n{source}')
    return '/* Generated by scripts/build_shop_shell.py; do not edit manually. */\n' + '\n'.join(chunks) + '\nhtml { font-size: 100%; }\n'
if __name__ == '__main__':
    (ROOT / 'css' / 'shop-shell.css').write_text(build())
